name : cramped_room"
lr: 1e-3
anneal_lr_fraction: 3.0
z_dim: 4
observation_shape: [26, 9, 5]

rshaped_horizon: 2.5e6
soup_reward: True
soup_reward_decay: False
ingred_reward: True
ingred_reward_decay: False

sp_timesteps: 7e6