name : cramped_room"
lr: 6e-4
anneal_lr_fraction: 1.5
z_dim: 4
observation_shape: [26, 5, 5]

rshaped_horizon: 2.5e6
soup_reward: True
soup_reward_decay: False
ingred_reward: True
ingred_reward_decay: False

sp_timesteps: 1e7