name : counter_circuit_o_1order
lr: 8e-4
anneal_lr_fraction: 3.0
z_dim: 6
observation_shape:  [26, 9, 5]

rshaped_horizon: 2.5e6
soup_reward: True
soup_reward_decay: False
ingred_reward: True
ingred_reward_decay: True

sp_timesteps: 8e6